config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :shows
  resources :seasons
  resources :ratings
  resources :episodes
  resources :quotes
  resources :clips
  resources :likes
  resources :lists
  resources :list_episodes do
    collection {post :sort }
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:new, :create]
  get 'auth/facebook/callback', to: 'sessions#create'
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  include PublicActivity::Model
  tracked except: :destroy, owner: ->(controller, model) { controller && controller.current_user }
  belongs_to :episode
  belongs_to :user
  has_many :likes, as: :likable, dependent: :destroy
  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy
  has_many :tags, as: :taggable, dependent: :destroy
  after_create :like_self

  protected
  def like_self
  	user.likes.create(likable_type: "Quote", likable_id: id, viewed: true)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
before_action :require_login

  def new
    @quote = Quote.new
    @show = Show.find(params[:show])
    @episode = params[:episode]
  end
  
  def create
    @quote = current_user.quotes.create(quote_params)
    
    respond_to do |format|
      format.html { redirect_to Episode.find(@quote.episode_id) }
      format.js
    end
  end
  
  def destroy
    @quote = Quote.find(params[:id])
    @id = @quote.id
    @quote.destroy
    
    respond_to do |format|
      format.html { redirect_to (:back) }
      format.js
    end
  end
  
  private
  
  def quote_params
    params.require(:quote).permit(:content, :user_id, :character, :episode_id)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_quote.html.erb
<% if params[:controller] != "static_pages" %>
<div class = "panel panel-default">
<% end %>
<div class="panel-body">
<div id = "quote_<%= quote.id %>">
  <p>
    "<%= quote.content %>"</br>
    -<strong><%= quote.character.titleize %></strong>
  </p>
  <div class = "uploader">
    Uploaded by</br> <%= link_to gravatar_for(User.find(quote.user_id), size: "20") + User.find(quote.user_id).name, user_path(User.find(quote.user_id)) %><br/>
  <% if quote.user == current_user %>
    <%= link_to 'delete quote', quote_path(quote.id), method: :delete, data: {confirm: "you sure?" }, remote: true %>
  <% end %>
  </div>
  <%= render partial: "shared/like_form", locals: {item_type: "Quote", item_id: quote.id} %>
  <small>Season <%= quote.episode.season.season_number %>: <%= link_to quote.episode.title, quote.episode %></small>
</div>
</div>
<% if params[:controller] != "static_pages" %>
</div>
<% end %>

app/views/quotes/_quotes_form.html.erb
<%= form_for @quote, remote: true do |f|%>
  <% if @episode == nil %>
  <%= select_tag :season_id,  options_for_select(@show.seasons.collect{ |s| [s.season_for_select, s.id] }), prompt: "Select a Season", required: true, class: "form-control" %>
  <%= f.grouped_collection_select :episode_id, @show.seasons, :episodes, :season_for_select, :id ,:episode_for_select, {include_blank: true, required: true}, {class: "form-control"} %>
  <% else %>
  <%= f.hidden_field :episode_id, value: @episode %>
  <% end %>
  <%= f.label :character, "Who said it?" %>
  <%= f.text_field :character, required: true, class: "form-control" %>
  <%= f.label :content, "Quote" %>
  <%= f.text_area :content, required: true, class: "form-control" %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/quotes/create.js.erb
$('#new_quote').remove();
$('#new_link').show();
var $item = $('<%= j render(@quote) %>');
$('.items').append($item).masonry('appended', $item);

app/views/quotes/destroy.js.erb
$('#quote_<%= j @id.to_s %>').remove();

app/views/quotes/new.js.erb
$('#new_link').hide().after('<%= j render("quotes_form") %>');