config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :shows
  resources :seasons
  resources :ratings
  resources :episodes
  resources :quotes
  resources :clips
  resources :likes
  resources :lists
  resources :list_episodes do
    collection {post :sort }
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:new, :create]
  get 'auth/facebook/callback', to: 'sessions#create'
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_like_form.html.erb
<div class = "like_button" id = "like_for_<%=item_type%>_<%= item_id %>" >
<% if Like.exists?(user_id: current_user, likable_type: item_type, likable_id: item_id) %>
  <%= link_to "", like_path(id: Like.find_by(user_id: current_user, likable_type: item_type, likable_id: item_id)), method: :delete, remote: true, class: "glyphicon glyphicon-heart" %>
  <% else %>
    <%= link_to "", likes_path(likable_type: item_type, likable_id: item_id), method: :post, remote: true, class: "glyphicon glyphicon-heart-empty" %>
<% end %>
<%= link_to "Share", new_tag_path(media_type: item_type, media_id: item_id), class: "btn btn-success", id: "tag_for_" + item_type + "_" + item_id.to_s, remote: true %>
  (<%= Like.where(likable_id: item_id, likable_type: item_type).count.to_s %>)
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<%= link_to gravatar_for(current_user), current_user %>
<span><%= link_to "view my profile", current_user %></span></br>
<span><%= pluralize(current_user.lists.count, "list") %></span>