config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :shows
  resources :seasons
  resources :ratings
  resources :episodes
  resources :quotes
  resources :clips
  resources :likes
  resources :lists
  resources :list_episodes do
    collection {post :sort }
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:new, :create]
  get 'auth/facebook/callback', to: 'sessions#create'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  default_scope { order('episode_number ASC') }
  belongs_to :season
  has_many :quotes
  has_many :clips
  has_many :list_episodes
  has_many :lists, through: :list_episodes
  
  def episode_for_select
    " Episode #{episode_number} #{title}"
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
    def show
      @episode = Episode.find(params[:id])
      items = @episode.quotes + @episode.clips
      @items = items.sort_by{ |item| item.likes.count }.reverse
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_episode.html.erb
<div class="episode" id="episode-<%= episode.id %>">
  <h3>
    <%= link_to(episode.title, episode_path(episode.id)) %>
    </h3>
    <% unless ListEpisode.exists?(list_id: List.find_by(user_id: current_user, show_id: episode.season.show_id), episode_id: episode.id)%>
      <%= link_to  "I Love this Episode", list_episodes_path(id: episode.id), method: :post, class: "btn btn-sm btn-primary", remote: true %></br>
    <% end %>
  
  <p>
    <%= episode.summary %>
  </p>
  <% if episode.buzzlisted != 0 %>
    <strong>
      buzzlisted <%= pluralize(episode.buzzlisted, 'time') %>
    </strong></br>
  <% end %>
  <%= link_to Clip.where(episode_id: episode).count.to_s + " Clips", episode_path(episode.id), class: "clips" %>
  <%= link_to Quote.where(episode_id: episode).count.to_s + " Quotes", episode_path(episode.id), class: "quotes" %>
</div>

app/views/episodes/show.html.erb
<% provide(:title, @episode.season.show.title + " | " + @episode.title) %>
  <div class="container" id="episode-display">
    <div class="row">
      <div class = "col-md-6 col-md-offset-3" id = "show-image">
        <%= link_to image_tag(@episode.season.show.thumbnail, width: "125"), show_path(@episode.season.show, season_id: @episode.season) %></br>
        Season <%= @episode.season.season_number %> Episode <%= @episode.episode_number %>
        <h1>
          <%= @episode.title %>
        </h1>  
      </div>
    </div>
    <div class = "row">
      <div class="col-md-4 col-md-offset-4">
        <div id="new_link">
          <%= link_to "Add a quote", new_quote_path(show: @episode.season.show, episode: @episode), remote: true, class: "btn btn-primary" %>
            <%= link_to "Add a clip", new_clip_path(show: @episode.season.show, episode: @episode), remote: true, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class='items transitions-enabled'>
        <%= render @items %>
      </div>
    </div>
  </div>