config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :shows
  resources :seasons
  resources :ratings
  resources :episodes
  resources :quotes
  resources :clips
  resources :likes
  resources :lists
  resources :list_episodes do
    collection {post :sort }
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:new, :create]
  get 'auth/facebook/callback', to: 'sessions#create'
end

app/models/list_episode.rb
class ListEpisode < ActiveRecord::Base
  include PublicActivity::Model
  tracked except: :destroy, owner: ->(controller, model) { controller && controller.current_user }
  belongs_to :list
  belongs_to :episode
  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy
  before_destroy :decrement_buzzlisted
  after_update :destroy_activity
  
  protected
  
  def decrement_buzzlisted
    episode.decrement(:buzzlisted)
    episode.save
  end

  def destroy_activity
    if ranking == 1
      activity_id = PublicActivity::Activity.find_by(trackable_id: id, trackable_type: "ListEpisode", key: "list_episode.update").id
      list_update_activities = PublicActivity::Activity.where(key:"list_episode.update")
      list_update_activities.each do |activity|
        if activity.trackable.list_id == list_id && activity.id != activity_id
          activity.destroy
        end
      end
    end
  end
end

app/controllers/list_episodes_controller.rb
class ListEpisodesController < ApplicationController
before_action :require_login

  def create
    episode = Episode.find(params[:id])
    show = episode.season.show
    list = List.find_or_create_by(user_id: current_user.id, show_id: show.id)
    @list_episode = list.list_episodes.create(episode_id: params[:id], ranking: list.list_episodes.size+1)
    episode = episode.increment(:buzzlisted)
    episode.save
  end
  
  def destroy
    list_episode = ListEpisode.find(params[:id])
    list_episode.destroy
    redirect_to (:back)
  end
  
  def sort
      params[:list_episode].each_with_index do |id, index|
          ListEpisode.update(id, ranking: index+1)
      end
  end
end

app/helpers/list_episodes_helper.rb
module ListEpisodesHelper
end

app/views/list_episodes/_list_episode.html.erb
<% if current_user == list_episode.list.user %>
  <%= content_tag_for :li, list_episode, class: "list-group-item" do %>
    <%= link_to list_episode.episode.title, episode_path(list_episode.episode_id) %>
    <small>
      Season <%= list_episode.episode.season.season_number %> Episode <%= list_episode.episode.episode_number %>
    </small>
    <%= link_to "Remove", list_episode_path(list_episode), method: :delete, class: "btn btn-danger btn-xs" %>
  <% end %>
  <% else %>
    <li class = "list-group-item">
      <%= link_to list_episode.episode.title, episode_path(list_episode.episode_id) %>
    <small>
      Season <%= list_episode.episode.season.season_number %> Episode <%= list_episode.episode.episode_number %>
    </small>
    </li>
<% end %>

app/views/list_episodes/create.js.erb
$("#episode-<%= j @list_episode.episode_id.to_s %>").load(location.href + " #episode-<%= j @list_episode.episode_id.to_s %> > *");
$("#show_navigation").load(location.href + " #show_navigation");